version: '3.8'

x-placement: &local-placement
  placement:
    constraints:
      - node.labels.pastvu.pastvu-data == true
x-defaults: &app-default
  image: ghcr.io/pastvu/backend:${TAG?ERR}
  configs:
    - source: config.js
      target: /code/config/local.config.js
  environment:
    - DOMAIN
    - PROTOCOL

services:

  fileserver:
    deploy: *local-placement
    image: ghcr.io/pastvu/fileserver:${TAG_FILESERVER?ERR}
    networks:
      - frontend
    volumes:
      - store:/store:ro
      - sitemap:/sitemap:ro

  frontend_ru:
    image: ghcr.io/pastvu/frontend:${TAG?ERR}

  frontend_en:
    image: ghcr.io/pastvu/frontend:${TAG_EN?ERR}

  app_primary:
    << : *app-default 
    networks:
      - backend
    deploy:
      << : *local-placement
      mode: global
    command: "bin/run --primary"

  app_ru:
    << : *app-default
    deploy: *local-placement
    networks:
      - frontend
      - backend
    volumes:
      - store:/store

  app_en:
    << : *app-default
    deploy: *local-placement
    image: ghcr.io/pastvu/backend:${TAG_EN?ERR}
    networks:
      - frontend
      - backend
    volumes:
      - store:/store

  notifier_ru:
    << : *app-default 
    networks:
      - backend
    deploy:
      << : *local-placement
      mode: global
    command: "bin/run --script notifier"

  notifier_en:
    << : *app-default 
    image: ghcr.io/pastvu/backend:${TAG_EN:?ERR}
    networks:
      - backend
    deploy: 
      << : *local-placement
      mode: global
    command: "bin/run --script notifier"

  uploader:
    << : *app-default
    deploy:
      << : *local-placement
      mode: global
    networks:
      - frontend
      - backend
    volumes:
      - store:/store
    command: "bin/run --script uploader"

  downloader:
    << : *app-default
    deploy: *local-placement
    networks:
      - frontend
      - backend
    volumes:
      - store:/store:ro
    command: "bin/run --script downloader"

  sitemap:
    << : *app-default
    deploy: *local-placement
    networks:
      - backend
    volumes:
      - sitemap:/sitemap
    command: "bin/run --script sitemap"

  worker:
    << : *app-default
    deploy:
      << : *local-placement
      mode: global
    networks:
      - backend
    command: "bin/run --script worker"

  api:
    << : *app-default
    networks:
      - backend

  mongo:
    deploy:
      << : *local-placement
      mode: global
    image: mongo:4.4
    networks:
      - backend
      - mongo
    volumes:
      - mongo4:/data/db

  redis:
    image: redis:6.2.6
    networks:
      - backend

configs:
  config.js:
    file: ${CONFIG:?ERR}
    name: pastvu_config_${CONFIG_TAG:?ERR}

networks:
  frontend:
  backend:
  mongo:
    attachable: true

volumes:
  store:
  sitemap:
  mongo4:
