version: '3.8'

x-defaults:
  &production-defaults
  logging:
    driver: local
    options:
      max-size: "100m"

services:

  fileserver:
    << : *production-defaults
    deploy:
      replicas: 10

  frontend_en:
    << : *production-defaults
    deploy:
      replicas: 5

  frontend_ru:
    << : *production-defaults
    deploy:
      replicas: 5

  mongo:
    << : *production-defaults

  app_ru:
    << : *production-defaults
    deploy:
      replicas: 10
    secrets:
      - pastvu_smtp_host
      - pastvu_smtp_user
      - pastvu_smtp_pass
      - pastvu_yandex_api_key
      - pastvu_google_api_key

  app_en:
    << : *production-defaults
    deploy:
      replicas: 5    
    secrets:
      - pastvu_smtp_host
      - pastvu_smtp_user
      - pastvu_smtp_pass
      - pastvu_yandex_api_key
      - pastvu_google_api_key

  api:
    << : *production-defaults
    deploy:
      replicas: 3

  uploader:
    << : *production-defaults

  downloader:
    << : *production-defaults
    deploy:
      replicas: 3

  worker:
    << : *production-defaults

  notifier_ru:
    << : *production-defaults
    secrets:
      - pastvu_smtp_host
      - pastvu_smtp_user
      - pastvu_smtp_pass
 
  notifier_en:
    << : *production-defaults
    secrets:
      - pastvu_smtp_host
      - pastvu_smtp_user
      - pastvu_smtp_pass

secrets:
  pastvu_smtp_host:
    external: true
  pastvu_smtp_user:
    external: true
  pastvu_smtp_pass:
    external: true
  pastvu_yandex_api_key:
    external: true
  pastvu_google_api_key:
    external: true
