version: '3.8'

x-staging:
  &staging-defaults
  logging:
    driver: local
    options:
      max-size: "512m"
  deploy:
    labels:
      swarmpit.service.deployment.autoredeploy: 'true'
  networks:
    - mailcatcher

services:

  api:
    << : *staging-defaults
    deploy:
      replicas: 1

  fileserver:
    << : *staging-defaults
    deploy:
      replicas: 1

  frontend_ru:
    << : *staging-defaults
    deploy:
      replicas: 1

  frontend_en:
    << : *staging-defaults
    deploy:
      replicas: 1

  app_ru:
    << : *staging-defaults
    deploy:
      replicas: 1

  app_en:
    << : *staging-defaults
    deploy:
      replicas: 1
    
  uploader:
    << : *staging-defaults
        
  downloader:
    << : *staging-defaults

  sitemap:
    << : *staging-defaults

  worker:
    << : *staging-defaults

  notifier_ru:
    << : *staging-defaults
 
  notifier_en:
    << : *staging-defaults

  mongo:
    << : *staging-defaults

networks:
  mailcatcher:
    external: true
