version: '3.8'

x-staging:
  &staging-defaults
  logging:
    options:
      max-size: "512m"
  deploy:
    labels:
      swarmpit.service.deployment.autoredeploy: 'true'
  networks:
    - mailcatcher

services:

  api:
    << : *staging-defaults
    deploy:
      replicas: 5

  fileserver:
    << : *staging-defaults
    deploy:
      replicas: 2

  frontend_ru:
    << : *staging-defaults
    deploy:
      replicas: 2

  frontend_en:
    << : *staging-defaults
    deploy:
      replicas: 2

  app_ru:
    << : *staging-defaults
    deploy:
      replicas: 4

  app_en:
    << : *staging-defaults
    deploy:
      replicas: 4
    
  uploader:
    << : *staging-defaults
        
  downloader:
    << : *staging-defaults

  sitemap:
    << : *staging-defaults

  notifier_ru:
    << : *staging-defaults
 
  notifier_en:
    << : *staging-defaults

  mongo:
    << : *staging-defaults

configs:
  config.js:
    file: ${CONFIG}
    name: pastvu_config_${CONFIG_TAG}

networks:
  mailcatcher:
    external: true

volumes:
  mongo:
