version: '3.8'

x-defaults:
  &production-defaults
  logging:
    options:
      max-size: "512m"

services:

  nginx:
    << : *production-defaults
    deploy:
      replicas: 40

  mongo:
    << : *production-defaults
    networks:
      - mongo

  app_ru:
    << : *production-defaults
    deploy:
      replicas: 10
    secrets:
      - pastvu_smtp_host
      - pastvu_smtp_user
      - pastvu_smtp_pass
      - pastvu_log_pass
      - pastvu_yandex_api_key
      - pastvu_google_api_key

  app_en:
    << : *production-defaults
    deploy:
      replicas: 10
    secrets:
      - pastvu_smtp_host
      - pastvu_smtp_user
      - pastvu_smtp_pass
      - pastvu_log_pass
      - pastvu_yandex_api_key
      - pastvu_google_api_key

  api:
    << : *production-defaults
    deploy:
      replicas: 5

  uploader:
    << : *production-defaults

  downloader:
    << : *production-defaults
    deploy:
      replicas: 3

  notifier_ru:
    << : *production-defaults
    secrets:
      - pastvu_smtp_host
      - pastvu_smtp_user
      - pastvu_smtp_pass
      - pastvu_log_pass
 
  notifier_en:
    << : *production-defaults
    secrets:
      - pastvu_smtp_host
      - pastvu_smtp_user
      - pastvu_smtp_pass
      - pastvu_log_pass

networks:
  mongo:
    driver: overlay
    attachable: true
  backend:

secrets:
  pastvu_smtp_host:
    external: true
  pastvu_smtp_user:
    external: true
  pastvu_smtp_pass:
    external: true
  pastvu_log_pass:
    external: true
  pastvu_yandex_api_key:
    external: true
  pastvu_google_api_key:
    external: true

configs:
  config.js:
    file: ${CONFIG:?ERR}
    name: pastvu_config_${CONFIG_TAG:?ERR}

volumes:
  mongo:
